# Generated by Django 4.2.13 on 2024-07-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storegrupozero', '0004_contacto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='MensajeContacto',
        ),
        migrations.RenameField(
            model_name='mensajecontacto',
            old_name='fecha_envio',
            new_name='fecha',
        ),
    ]
