# Generated by Django 4.2 on 2024-07-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storegrupozero', '0005_rename_contacto_mensajecontacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='mensaje_cifrado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
